# Generated by Django 5.2.7 on 2025-11-08 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('vehicle', '0005_vehicle_created_at_vehicle_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('pre', 'Pre-Rental'), ('post', 'Post-Rental')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('fuel_level', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='booking.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePartObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_key', models.CharField(max_length=100)),
                ('part_label', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('scratch', 'Scratch'), ('dent', 'Dent'), ('broken', 'Broken')], default='good', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/parts/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='report.vehicleinspectionreport')),
            ],
        ),
    ]
