# Generated by Django 5.2.7 on 2025-11-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepartobservation',
            name='report',
        ),
        migrations.DeleteModel(
            name='VehicleInspectionReport',
        ),
        migrations.DeleteModel(
            name='VehiclePartObservation',
        ),
    ]
