# Generated by Django 5.2.7 on 2025-10-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('motorbike', 'Motorbike')], max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('id_available', models.BooleanField(default=True)),
            ],
        ),
    ]
