# Generated by Django 5.2.7 on 2025-10-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='id_available',
            new_name='is_available',
        ),
    ]
