# Generated by Django 5.2.7 on 2025-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_id_available_vehicle_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_available',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
