# Generated by Django 5.2.7 on 2025-11-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicle_created_at_vehicle_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
    ]
