# Generated by Django 5.2.7 on 2025-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cliq', 'Cliq')], default='cash', max_length=20),
        ),
    ]
