# Generated by Django 5.2.7 on 2025-11-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='driver_licens_number',
            new_name='driver_license_number',
        ),
    ]
