# Generated by Django 5.2.7 on 2025-10-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_user_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
