# Generated by Django 5.2.7 on 2025-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_driver_licens_number_customer_driver_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Unverified', 'Unverified'), ('Blocked', 'Blocked')], default='Unverified', max_length=20),
        ),
    ]
