# Generated by Django 5.2.7 on 2025-10-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='driver_licens_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
